### ISSUE TITLE
Using two WiiMotes as indiviual Controller mapped to Keyboard

### ISSUE THREAD

**Issue by Zetabite** [Ryochan7/sc-controller#34]
I would like to use two WiiMotes for individual input, mapped to keyboard keys. For use especially in Lego Star Wars III

**Comment by Ryochan7** [comment]
It depends on what type of configuration you would want. The Linux kernel splits the Wiimote into several different devices depending on what extensions might be plugged in at the time. It has been a while since I used a Wiimote so I cannot remember how a typical config is set up but I think my MotionPlus TR is exposed as 3 devices.

You would probably have to find the device that is the main Wiimote and then map it to an SDL2 GameController config to use it. You should be able to map the buttons to keyboard keys in the GUI after that.

Another mapper option that I have used for the Wiimote in the past is MoltenGamepad. That project has direct Wiimote support and it might be easier to configure for this use case.

https://github.com/jgeumlek/MoltenGamepad
